services:
  pelita-webtournament:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: debilski/pelita-webtournament
    container_name: pelita-webtournament
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped

